import React, { useState } from 'react';
import {
  ChevronDown,
  ChevronUp,
  ArrowRight,
  ShieldCheck,
  Zap,
  Sparkles,
  Lock,
  BookOpen,
  ArrowUpRight,
  HelpCircle,
  Layers,
  CheckCircle2,
  Check
} from 'lucide-react';
import { ToolItem, UserUsage } from '../../types';
import { TOOLS_LIST } from '../../data/tools';
import { ARTICLES_DATA } from '../../data/articles';
import { Breadcrumbs } from '../layout/Breadcrumbs';
import { ToolVisualPreview } from '../common/ToolVisualPreview';
import { ArticleVisualPreview } from '../common/ArticleVisualPreview';
import { VisualToolCard } from './VisualToolCard';

interface ToolPageContainerProps {
  tool: ToolItem;
  onNavigate: (path: string) => void;
  children: React.ReactNode;
  usage?: UserUsage;
  onOpenAuth?: () => void;
}

export const ToolPageContainer: React.FC<ToolPageContainerProps> = ({
  tool,
  onNavigate,
  children,
  usage,
  onOpenAuth,
}) => {
  const [openFaqIdx, setOpenFaqIdx] = useState<number | null>(0);

  // Map category to label
  const categoryLabels: Record<string, string> = {
    ai: 'AI Tools',
    image: 'Image Tools',
    pdf: 'PDF Suite',
    calculators: 'Calculators',
    text: 'Text & Utilities',
  };

  const categoryPath = `/${tool.category === 'text' ? 'text-tools' : `${tool.category}-tools`}`;
  const categoryLabel = categoryLabels[tool.category] || 'Tools';

  // Breadcrumbs config
  const breadcrumbItems = [
    { label: 'Home', path: '/' },
    { label: categoryLabel, path: categoryPath },
    { label: tool.name, path: tool.path },
  ];

  // Dynamic FAQs tailored to tool category
  const getFaqsForTool = () => {
    if (tool.category === 'ai') {
      return [
        {
          q: `Is the ${tool.name} free to use?`,
          a: `Yes! Guest users receive 5 daily generations without signing in. Creating a free verified account immediately grants 15 generations per day, while Pro subscribers enjoy 500 daily requests.`
        },
        {
          q: 'Which AI model powers this generator?',
          a: 'This tool is powered server-side by Google Gemini 2.5 Flash, providing state-of-the-art natural language intelligence with sub-second response latencies.'
        },
        {
          q: 'Can I use the generated content commercially?',
          a: 'Absolutely. All captions, bios, hashtags, and rewritten copy generated by ToolVerse AI are 100% royalty-free for personal, corporate, and commercial use.'
        },
        {
          q: 'Is my input prompt stored or trained on?',
          a: 'No. Prompts are transmitted via encrypted TLS directly to our server-side proxy solely to generate your response, and are never saved or used to train third-party models.'
        }
      ];
    }
    if (tool.category === 'pdf') {
      return [
        {
          q: 'Does ToolVerse AI upload my PDF documents to a cloud server?',
          a: 'Never. Our PDF tools leverage client-side WebAssembly, Mozilla PDF.js, and pdf-lib directly inside your browser sandbox. Your sensitive files never leave your local device.'
        },
        {
          q: 'Is there a file size limit for PDF processing?',
          a: 'Because processing executes in your browser memory, we comfortably handle files up to 100MB without performance degradation.'
        },
        {
          q: 'Will formatting or text fonts be distorted during conversion?',
          a: 'No. We preserve high-DPI rasterization and embedded font vectors to ensure crisp text clarity across all viewing devices.'
        },
        {
          q: 'Can I convert multiple pages at once?',
          a: 'Yes. Multi-page PDFs are automatically parsed and batch rendered with progress indicators.'
        }
      ];
    }
    if (tool.category === 'image') {
      return [
        {
          q: 'Does compressing or resizing images reduce visual clarity?',
          a: 'Our smart bicubic algorithms strip unnecessary EXIF metadata and optimize color quantization without degrading visible fidelity.'
        },
        {
          q: 'Are my images stored on any server?',
          a: 'Zero server storage. The entire manipulation happens directly in your browser using HTML5 Canvas and WebGL acceleration.'
        },
        {
          q: 'Which image file formats are supported?',
          a: 'We support JPG, JPEG, PNG, WebP, SVG, and GIF formats with instant cross-conversion capabilities.'
        },
        {
          q: 'Can I process high-resolution photography?',
          a: 'Yes, images up to 4K and 8K resolution can be resized, converted, or compressed directly on your machine.'
        }
      ];
    }
    return [
      {
        q: `How accurate is the ${tool.name}?`,
        a: 'Our computational formulas adhere to standard financial and mathematical specifications, calculating results to high floating-point precision.'
      },
      {
        q: 'Can I export or copy the calculation results?',
        a: 'Yes. Every calculation summary includes 1-click clipboard copying and visual breakdown tables.'
      },
      {
        q: 'Does this tool work offline or in airplane mode?',
        a: 'Yes! Because this utility runs purely on client-side JavaScript, once loaded it continues to calculate without an active internet connection.'
      }
    ];
  };

  const faqs = getFaqsForTool();

  // Related Tools
  const relatedTools = TOOLS_LIST.filter(
    (t) => t.id !== tool.id && (t.category === tool.category || t.popular)
  ).slice(0, 3);

  // Related Articles
  const relatedArticles = ARTICLES_DATA.filter(
    (a) => a.relatedToolSlugs.includes(tool.id) || a.category === tool.category
  ).slice(0, 2);

  return (
    <div className="min-h-screen tv-tool-shell py-6 sm:py-10">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Breadcrumb Navigation */}
        <div className="mb-6">
          <Breadcrumbs items={breadcrumbItems} onNavigate={onNavigate} />
        </div>

        {/* Dedicated Professional Workspace Header with Relevant Visual */}
        <div className="tv-workspace-card overflow-hidden mb-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 items-center">
            
            {/* Left: Metadata & Details */}
            <div className="lg:col-span-8 p-6 sm:p-8 tv-workspace-gradient">
              <div className="flex flex-wrap items-center gap-2 mb-3">
                <span className="px-2.5 py-1 rounded-md text-[10px] font-black uppercase tracking-wider bg-slate-100 text-slate-700 border border-slate-200">
                  {categoryLabel}
                </span>
                
                {tool.category === 'ai' ? (
                  <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[10px] font-bold tracking-wider bg-indigo-50 text-indigo-700 border border-indigo-200">
                    <Sparkles className="w-3 h-3 text-indigo-600" />
                    Gemini 2.5 Flash Engine
                  </span>
                ) : (
                  <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[10px] font-bold tracking-wider bg-emerald-50 text-emerald-700 border border-emerald-200">
                    <ShieldCheck className="w-3 h-3 text-emerald-600" />
                    100% In-Browser Privacy
                  </span>
                )}

                <span className="inline-flex items-center gap-1 text-[10px] font-bold text-slate-500">
                  ⚡ Instant Execution
                </span>
              </div>

              <h1 className="text-2xl sm:text-3xl lg:text-4xl font-black text-slate-900 tracking-tight">
                {tool.name}
              </h1>
              <p className="mt-2 text-sm sm:text-base text-slate-600 leading-relaxed max-w-2xl font-normal">
                {tool.description}
              </p>

              {/* Key Benefits Pills */}
              <div className="flex flex-wrap items-center gap-3 mt-4 pt-4 border-t border-slate-100 text-xs font-semibold text-slate-600">
                <span className="flex items-center gap-1 text-emerald-700">
                  <Check className="w-3.5 h-3.5" /> No file uploads to cloud
                </span>
                <span className="text-slate-300 hidden sm:inline">•</span>
                <span className="flex items-center gap-1 text-emerald-700">
                  <Check className="w-3.5 h-3.5" /> 100% Free to use
                </span>
                <span className="text-slate-300 hidden sm:inline">•</span>
                <span className="flex items-center gap-1 text-emerald-700">
                  <Check className="w-3.5 h-3.5" /> Zero watermarks
                </span>
              </div>

              {/* AI Quota Meter if applicable */}
              {tool.category === 'ai' && usage && (
                <div className="mt-4 p-3 rounded-xl bg-slate-50 border border-slate-200 flex flex-wrap items-center justify-between gap-3 text-xs">
                  <div className="flex items-center gap-2">
                    <Zap className="w-4 h-4 text-amber-500" />
                    <span className="font-bold text-slate-800">
                      Daily Quota ({usage.plan}): {Math.max(0, usage.dailyGenerationsLimit - usage.dailyGenerationsUsed)} / {usage.dailyGenerationsLimit} requests left
                    </span>
                  </div>
                  {usage.plan === 'guest' && onOpenAuth && (
                    <button
                      onClick={onOpenAuth}
                      className="text-xs font-bold text-indigo-600 hover:text-indigo-800 flex items-center gap-1 cursor-pointer"
                    >
                      <span>Sign in for 15 daily requests</span>
                      <ArrowRight className="w-3 h-3" />
                    </button>
                  )}
                </div>
              )}
            </div>

            {/* Right: Visual Illustration preview banner */}
            <div className="lg:col-span-4 p-4 lg:p-6 bg-white/75 border-t lg:border-t-0 lg:border-l border-indigo-100/60 flex items-center justify-center">
              <div className="w-full max-w-[300px]">
                <div className="text-[10px] font-black uppercase tracking-wider text-slate-400 mb-1.5 flex items-center justify-between">
                  <span>Interactive Workflow</span>
                  <span className="text-indigo-600 font-bold">Live Preview</span>
                </div>
                <div className="rounded-2xl border border-slate-200 bg-white overflow-hidden shadow-xs">
                  <ToolVisualPreview toolId={tool.id} size="md" />
                </div>
              </div>
            </div>

          </div>
        </div>

        {/* Tool Workspace Component */}
        <div className="mb-14 tv-form">
          {children}
        </div>

        {/* How to Use in 3 Simple Steps */}
        <div className="bg-white rounded-3xl border border-slate-200/90 shadow-2xs p-6 sm:p-10 mb-10">
          <div className="text-center max-w-xl mx-auto mb-8">
            <span className="text-[11px] font-black uppercase tracking-wider text-indigo-600 bg-indigo-50 px-3 py-1 rounded-full">
              Simple 3-Step Workflow
            </span>
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight mt-2">
              How to Use {tool.name}
            </h2>
            <p className="text-xs sm:text-sm text-slate-500 mt-1">
              Streamlined, no complicated software installation or account creation required.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="p-5 rounded-2xl bg-slate-50/70 border border-slate-100 flex flex-col">
              <div className="w-8 h-8 rounded-xl bg-slate-950 text-white font-black text-sm flex items-center justify-center mb-3">
                1
              </div>
              <h3 className="text-sm font-bold text-slate-900 mb-1">
                Provide Input or Upload
              </h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Enter your topic, paste your text, or drag and drop your file into the secure workspace above.
              </p>
            </div>

            <div className="p-5 rounded-2xl bg-slate-50/70 border border-slate-100 flex flex-col">
              <div className="w-8 h-8 rounded-xl bg-indigo-600 text-white font-black text-sm flex items-center justify-center mb-3">
                2
              </div>
              <h3 className="text-sm font-bold text-slate-900 mb-1">
                Configure & Process
              </h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Customize your options (tone, target format, quality threshold) and click the primary action button to process instantly.
              </p>
            </div>

            <div className="p-5 rounded-2xl bg-slate-50/70 border border-slate-100 flex flex-col">
              <div className="w-8 h-8 rounded-xl bg-emerald-600 text-white font-black text-sm flex items-center justify-center mb-3">
                3
              </div>
              <h3 className="text-sm font-bold text-slate-900 mb-1">
                Download or Copy
              </h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Inspect your generated output or preview your processed document, then copy to clipboard or download with one click.
              </p>
            </div>
          </div>
        </div>

        {/* Enterprise Highlights Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-10">
          <div className="bg-white p-5 rounded-2xl border border-slate-200/90 shadow-2xs">
            <ShieldCheck className="w-6 h-6 text-emerald-600 mb-2" />
            <h4 className="text-xs font-bold text-slate-900">Privacy Safeguarded</h4>
            <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">
              Calculations and document manipulations run entirely in your local browser sandbox.
            </p>
          </div>

          <div className="bg-white p-5 rounded-2xl border border-slate-200/90 shadow-2xs">
            <Zap className="w-6 h-6 text-amber-500 mb-2" />
            <h4 className="text-xs font-bold text-slate-900">High-Speed Execution</h4>
            <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">
              Near-instant calculations and sub-second generation latencies minimize downtime.
            </p>
          </div>

          <div className="bg-white p-5 rounded-2xl border border-slate-200/90 shadow-2xs">
            <Layers className="w-6 h-6 text-indigo-600 mb-2" />
            <h4 className="text-xs font-bold text-slate-900">Enterprise Standards</h4>
            <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">
              Standard-compliant rasterization, modern WebP/PDF streams, and mathematical precision.
            </p>
          </div>

          <div className="bg-white p-5 rounded-2xl border border-slate-200/90 shadow-2xs">
            <CheckCircle2 className="w-6 h-6 text-cyan-600 mb-2" />
            <h4 className="text-xs font-bold text-slate-900">Zero Installation</h4>
            <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">
              No heavy software downloads or browser extensions. Works across desktop and mobile.
            </p>
          </div>
        </div>

        {/* Frequently Asked Questions */}
        <div className="bg-white rounded-3xl border border-slate-200/90 shadow-2xs p-6 sm:p-10 mb-10">
          <div className="flex items-center gap-2 mb-6">
            <HelpCircle className="w-5 h-5 text-indigo-600" />
            <h2 className="text-lg sm:text-xl font-black text-slate-900 tracking-tight">
              Frequently Asked Questions
            </h2>
          </div>

          <div className="divide-y divide-slate-100">
            {faqs.map((faq, idx) => {
              const isOpen = openFaqIdx === idx;
              return (
                <div key={idx} className="py-4">
                  <button
                    onClick={() => setOpenFaqIdx(isOpen ? null : idx)}
                    className="w-full flex items-center justify-between text-left text-sm font-bold text-slate-800 hover:text-indigo-600 transition-colors cursor-pointer"
                  >
                    <span>{faq.q}</span>
                    {isOpen ? (
                      <ChevronUp className="w-4 h-4 text-slate-400 shrink-0 ml-2" />
                    ) : (
                      <ChevronDown className="w-4 h-4 text-slate-400 shrink-0 ml-2" />
                    )}
                  </button>
                  {isOpen && (
                    <p className="mt-2 text-xs sm:text-sm text-slate-600 leading-relaxed pr-6 animate-in fade-in duration-150">
                      {faq.a}
                    </p>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Related Tools with Visual Cards */}
        <div className="mb-10">
          <div className="flex items-center justify-between mb-5">
            <div>
              <span className="text-[10px] font-black uppercase tracking-wider text-indigo-600 bg-indigo-50 px-2.5 py-0.5 rounded">
                Continue Exploring
              </span>
              <h3 className="text-lg sm:text-xl font-black text-slate-900 tracking-tight mt-1">
                Related Production Tools
              </h3>
            </div>
            <button
              onClick={() => onNavigate(categoryPath)}
              className="text-xs font-bold text-indigo-600 hover:underline flex items-center gap-1 cursor-pointer"
            >
              <span>Explore all in {categoryLabel}</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {relatedTools.map((rel) => (
              <VisualToolCard key={rel.id} tool={rel} onNavigate={onNavigate} />
            ))}
          </div>
        </div>

        {/* Related Editorial Guides with Thumbnails */}
        {relatedArticles.length > 0 && (
          <div className="bg-white rounded-3xl border border-slate-200/90 shadow-2xs p-6 sm:p-8">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-2">
                <BookOpen className="w-5 h-5 text-indigo-600" />
                <h3 className="text-base sm:text-lg font-black text-slate-900 tracking-tight">
                  Educational Guides & Technical Tutorials
                </h3>
              </div>
              <button
                onClick={() => onNavigate('/blog')}
                className="text-xs font-bold text-indigo-600 hover:underline flex items-center gap-1 cursor-pointer"
              >
                <span>Browse all guides</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {relatedArticles.map((art) => (
                <div
                  key={art.id}
                  onClick={() => onNavigate(`/blog/${art.slug}`)}
                  className="p-4 rounded-2xl border border-slate-200/80 hover:border-indigo-300 bg-slate-50/40 hover:bg-white shadow-2xs hover:shadow-xs transition-all cursor-pointer flex flex-col justify-between group"
                >
                  <div>
                    <ArticleVisualPreview article={art} size="card" className="mb-3" />
                    <div className="flex items-center justify-between text-[11px] text-slate-400 font-semibold mb-1">
                      <span className="uppercase text-indigo-600 font-bold">{art.category}</span>
                      <span>{art.readTime}</span>
                    </div>
                    <h4 className="text-sm font-bold text-slate-900 group-hover:text-indigo-600 transition-colors line-clamp-1">
                      {art.title}
                    </h4>
                    <p className="text-xs text-slate-500 line-clamp-2 mt-1 font-normal">
                      {art.summary}
                    </p>
                  </div>
                  <div className="mt-3 pt-2 border-t border-slate-100 flex items-center justify-between text-xs font-bold text-indigo-600">
                    <span>Read tutorial</span>
                    <ArrowUpRight className="w-3.5 h-3.5 transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform" />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

      </div>
    </div>
  );
};


      </div>
    </div>
  );
};
